"use strict";
const moment = require("moment");

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("tasks", [
      {
        title: "Otimização da interface",
        description: "Devemos deixar a interface mais fluida",
        task_points: 100,
        created_at: moment(new Date()).format("MM/DD/YYYY"),
        updated_at: moment(new Date()).format("MM/DD/YYYY"),
        task_column_id: 1,
        task_board_id: 1,
        user_id: 2,
      },
      {
        title: "Finalização do layout do login",
        description: "Adicionar inputs e estilização",
        task_points: 100,
        created_at: moment(new Date()).format("MM/DD/YYYY"),
        updated_at: moment(new Date()).format("MM/DD/YYYY"),
        task_column_id: 1,
        task_board_id: 1,
        user_id: 3,
      },
      {
        title: "Otimização do dashboard",
        description: "Deveremos otimizar a dashboard",
        task_points: 100,
        created_at: moment(new Date()).format("MM/DD/YYYY"),
        updated_at: moment(new Date()).format("MM/DD/YYYY"),
        task_column_id: 1,
        task_board_id: 1,
        user_id: 4,
      },
      {
        title: "Ajustes na UX",
        description: " Melhorar o posicionamento dos botões e hovers",
        task_points: 100,
        created_at: moment(new Date()).format("MM/DD/YYYY"),
        updated_at: moment(new Date()).format("MM/DD/YYYY"),
        task_column_id: 1,
        task_board_id: 1,
        user_id: 5,
      },
      {
        title: "Refatoração do ER",
        description: "Adicionar tabelas intermediárias",
        task_points: 100,
        created_at: moment(new Date()).format("MM/DD/YYYY"),
        updated_at: moment(new Date()).format("MM/DD/YYYY"),
        task_column_id: 1,
        task_board_id: 2,
        user_id: 7,
      },
      {
        title: "Finalizar rotas de autenticação",
        description: "Criar e enviar tokens por JWT",
        task_points: 100,
        created_at: moment(new Date()).format("MM/DD/YYYY"),
        updated_at: moment(new Date()).format("MM/DD/YYYY"),
        task_column_id: 1,
        task_board_id: 2,
        user_id: 8,
      },
      {
        title: "Finalizar a integração",
        description: "Ajustes nas chamadas da API e respostas do servidor",
        task_points: 100,
        created_at: moment(new Date()).format("MM/DD/YYYY"),
        updated_at: moment(new Date()).format("MM/DD/YYYY"),
        task_column_id: 1,
        task_board_id: 2,
        user_id: 9,
      },
      {
        title: "Finalização da configuração dos protocolos",
        description:
          "Ajustar a segurança do sistema adicionando protocolos https",
        task_points: 100,
        created_at: moment(new Date()).format("MM/DD/YYYY"),
        updated_at: moment(new Date()).format("MM/DD/YYYY"),
        task_column_id: 1,
        task_board_id: 2,
        user_id: 10,
      },
      {
        title: "Criar rotas do backend",
        description: "Criação das rotas do backend, get post put delete",
        task_points: 100,
        created_at: new Date("05-08-2020"),
        updated_at: new Date("05-09-2020"),
        task_column_id: 3,
        task_board_id: 4,
        user_id: 12,
      },
      {
        title: "Adicionar testes",
        description:
          "Adicionar os testes para validar as rotas, inclusão de testes automatizados",
        task_points: 100,
        created_at: new Date("05-08-2020"),
        updated_at: new Date("05-10-2020"),
        task_column_id: 3,
        task_board_id: 4,
        user_id: 13,
      },
      {
        title: "Adicionar validação de dados",
        description: "Verificar o tipo e formato dos dados vindos do frontend",
        task_points: 100,
        created_at: new Date("05-08-2020"),
        updated_at: new Date("05-11-2020"),
        task_column_id: 3,
        task_board_id: 4,
        user_id: 14,
      },
      {
        title: "Externalizar funções para reaproveitamento",
        description:
          "Criar pasta de utils e adicionar funções para serem reutilizadas",
        task_points: 100,
        created_at: new Date("05-08-2020"),
        updated_at: new Date("05-15-2020"),
        task_column_id: 3,
        task_board_id: 4,
        user_id: 15,
      },
      {
        title: "Verificar rotas, incluir middlewares",
        description: "Separar as responsabilidades dos arquivos",
        task_points: 100,
        created_at: new Date("05-08-2020"),
        updated_at: new Date("05-22-2020"),
        task_column_id: 3,
        task_board_id: 4,
        user_id: 16,
      },
      {
        title: "Transferir páginas HTML para JSX",
        description:
          "Alternar os arquivos e fazer as mudanças necessárias para nova versão.",
        task_points: 100,
        created_at: new Date("05-23-2020"),
        updated_at: new Date("05-24-2020"),
        task_column_id: 3,
        task_board_id: 5,
        user_id: 12,
      },
      {
        title: "Componentização das páginas",
        description: "Separar arquivos em componentes.",
        task_points: 100,
        created_at: new Date("05-23-2020"),
        updated_at: new Date("05-26-2020"),
        task_column_id: 3,
        task_board_id: 5,
        user_id: 13,
      },
      {
        title: "Tornar landing page responsiva",
        description: "Criar menu mobile e ajustar posicionamento das seções",
        task_points: 100,
        created_at: new Date("05-23-2020"),
        updated_at: new Date("05-28-2020"),
        task_column_id: 3,
        task_board_id: 5,
        user_id: 14,
      },
      {
        title: "Salvar token no localStorage",
        description:
          "Armazenar dados e token no localStorage para reaproveitamento.",
        task_points: 100,
        created_at: new Date("05-23-2020"),
        updated_at: new Date("05-30-2020"),
        task_column_id: 3,
        task_board_id: 5,
        user_id: 15,
      },
      {
        title: "Validação das rotas no frontend",
        description:
          "Adicionar verificação para o usuário acessar apenas rotas permitidas a ele",
        task_points: 100,
        created_at: new Date("05-23-2020"),
        updated_at: new Date("06-06-2020"),
        task_column_id: 3,
        task_board_id: 5,
        user_id: 16,
      },
      {
        title: "Adicionar Biblioteca Axios",
        description: "Adicionar biblioteca axios para requições HTTP",
        task_points: 100,
        created_at: new Date("06-08-2020"),
        updated_at: new Date("06-12-2020"),
        task_column_id: 3,
        task_board_id: 6,
        user_id: 12,
      },
      {
        title: "Integração da Dashboard do Owner",
        description: "Exibir gráficos para o usuário owner - empresa",
        task_points: 100,
        created_at: new Date("06-08-2020"),
        updated_at: new Date("06-13-2020"),
        task_column_id: 3,
        task_board_id: 6,
        user_id: 13,
      },
      {
        title: "Integração da página de times",
        description: "Exibir os times em que o usuário já é participante",
        task_points: 100,
        created_at: new Date("06-08-2020"),
        updated_at: new Date("06-15-2020"),
        task_column_id: 3,
        task_board_id: 6,
        user_id: 14,
      },
      {
        title: "Realizar o logout",
        description: "Implementar a função de logout.",
        task_points: 100,
        created_at: new Date("06-08-2020"),
        updated_at: new Date("06-19-2020"),
        task_column_id: 3,
        task_board_id: 6,
        user_id: 15,
      },
      {
        title: "Integrar dashboard collaborator",
        description:
          "Exibir gráficos para o colaborador e listar tarefas/dailys",
        task_points: 100,
        created_at: new Date("06-08-2020"),
        updated_at: new Date("06-22-2020"),
        task_column_id: 3,
        task_board_id: 6,
        user_id: 16,
      },
      {
        title: "Correção de gráficos de burndown",
        description: "Bug em relação a cáuculo dos pontos",
        task_points: 100,
        created_at: new Date("06-23-2020"),
        updated_at: new Date("06-23-2020"),
        task_column_id: 3,
        task_board_id: 7,
        user_id: 12,
      },
      {
        title: "Correção de NAN no gráfico do time",
        description: "Na página do time, retornado NAN no gráfico",
        task_points: 100,
        created_at: new Date("06-23-2020"),
        updated_at: new Date("06-24-2020"),
        task_column_id: 3,
        task_board_id: 7,
        user_id: 13,
      },
      {
        title: "Corrigir limite do texto no card de daily",
        description: "Texto saindo da div e quebrando o layout da página.",
        task_points: 100,
        created_at: new Date("06-23-2020"),
        updated_at: new Date("06-28-2020"),
        task_column_id: 3,
        task_board_id: 7,
        user_id: 14,
      },
      {
        title: "Corrigir formatação do card de tarefas",
        description: "Ajustar texto para não ficar assimétrico em relação ao card",
        task_points: 100,
        created_at: new Date("06-23-2020"),
        updated_at: new Date("07-03-2020"),
        task_column_id: 3,
        task_board_id: 7,
        user_id: 15,
      },
      {
        title: "Bug estranho ocorrendo ao deletar usuário do time",
        description:
          "Verificar bug ao deletar usuário do time, sistema API para de funcionar.",
        task_points: 100,
        created_at: new Date("06-23-2020"),
        updated_at: new Date("07-04-2020"),
        task_column_id: 3,
        task_board_id: 7,
        user_id: 16,
      },
      {
        title: "Revisão envio de e-mail",
        description: "Revisão template de e-mail",
        task_points: 100,
        created_at: new Date('07-07-2020'),
        updated_at: new Date("07-07-2020"),
        task_column_id: 3,
        task_board_id: 8,
        user_id: 12,
      },
      {
        title: "Revisão autenticação do usuário no sistema",
        description: "Verificar a autenticação do usuário nos sistema.",
        task_points: 100,
        created_at: new Date('07-07-2020'),
        updated_at: new Date("07-09-2020"),
        task_column_id: 3,
        task_board_id: 8,
        user_id: 13,
      },
      {
        title: "Revisão seeders para apresentação do sistema",
        description: "Verificar e corrigir seeders para apresentação do sistema.",
        task_points: 100,
        created_at: new Date('07-07-2020'),
        updated_at: new Date("07-09-2020"),
        task_column_id: 3,
        task_board_id: 8,
        user_id: 14,
      },
      {
        title: "Revisar slides para aprenstação do sistema",
        description: "Revisar slides para alinhar com as falas durante a apresentação.",
        task_points: 100,
        created_at: new Date('07-07-2020'),
        updated_at: new Date("07-10-2020"),
        task_column_id: 3,
        task_board_id: 8,
        user_id: 15,
      },
      {
        title: "Revisar scripts de fala para apresentação",
        description:
          "Alinhar falas com os demais componentes do time",
        task_points: 100,
        created_at: new Date('07-07-2020'),
        updated_at: new Date("07-11-2020"),
        task_column_id: 3,
        task_board_id: 8,
        user_id: 16,
      },
      {
        title: "Conclusão das seeders para apresentação",
        description: "Validação dos dados das seeders para apresentação",
        task_points: 100,
        created_at: new Date('07-12-2020'),
        updated_at: new Date("07-12-2020"),
        task_column_id: 3,
        task_board_id: 9,
        user_id: 12,
      },
      {
        title: "Concluir validação dos teste no sistema",
        description: "Validação do sistema para encontrar falhas.",
        task_points: 100,
        created_at: new Date('07-12-2020'),
        updated_at: new Date("07-12-2020"),
        task_column_id: 3,
        task_board_id: 9,
        user_id: 13,
      },
      {
        title: "Concluir slides para apresentação",
        description: "concluir slides para a apresentação e apresentar em equipe.",
        task_points: 100,
        created_at: new Date('07-12-2020'),
        updated_at: new Date("07-15-2020"),
        task_column_id: 3,
        task_board_id: 9,
        user_id: 14,
      },
      {
        title: "Lançar tag da versão de 1.0 do sistema",
        description: "Concluir o lançamento do sistema com a criação da tag 1.0",
        task_points: 100,
        created_at: new Date('07-12-2020'),
        updated_at: new Date("07-15-2020"),
        task_column_id: 3,
        task_board_id: 9,
        user_id: 15,
      },
      {
        title: "Concluir scripts para apresentação",
        description:
          "Alinhar falas finais com os demais componentes do time",
        task_points: 100,
        created_at: new Date('07-12-2020'),
        updated_at: new Date("07-12-2020"),
        task_column_id: 2,
        task_board_id: 9,
        user_id: 16,
      },
    ]);
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("tasks", null, {});
  },
};
